services:
  - type: web
    name: text-detection-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py 